### PR TITLE
dropdown/toggle controller improvements

### PR DESCRIPTION
**Pull request by plummip**
https://github.com/boxture/oms/issues/3180

### CODE REVIEW

**Comment by plummip** [comment]
see latest comment on ticket for more details

**Comment by rparse** [comment]
Hello @plummip,

Reviewed the code and also testing it on local and found below  - 

1. On table filters if we filter by giving some value it works fine, if we clear filter it doesn't clear filter 
Screenshot 2023-07-26 at 10 58 30 AM (3)

2. If there are too may entries in dropdown after scrolling all entries are not visible
Screenshot 2023-07-26 at 10 58 04 AM (3)

attached screenshot for the same, still testing the code

**Review by rparse — CHANGES_REQUESTED** [review]
Added some testing feedback, please check

**Comment by rparse** [comment]
> Added some testing feedback, please check

Verified all above with latest updated code all are working fine!
Approved PR

**Review by rparse — APPROVED** [review]
Changes verified!

**Pull request merged**
